ENV_NAME: "MultiAnt-v0"
TEMPLATE: "./envs/race/assets/multi_ant.xml"
RNG_SEED: 42

USE_GPU: True
DEVICE: "cuda:0"

MAPPO:
  LR: 5.e-4
  CRITIC_LR: 5.e-4
  USE_LINEAR_LR_DECAY: False

ENV:
  EPISODE_LENGTH: 1000
  TERMINATE_WHEN_UNHEALTHY: True
  USE_RELATIVE_OBS: True
  USE_NOISE: False

EMAT:
  AGENT_NUM: 3
  N_TRAINING_THREADS: 15
  N_ROLLOUT_THREADS: 15
  N_EVAL_ROLLOUT_THREADS: 1
  N_RENDER_ROLLOUT_THREADS: 1
  NUM_ENV_STEPS: 30e6

TEMPLATE: "./envs/assets/multi_ant.xml"

NETWORK:
  SHARE_POLICY: False
  USE_RELU: False
  HIDDEN_SIZE: 64
  LAYER_N: 2
  USE_CENTRALIZED_V: False

EVAL_PERIOD: 2