ENV_NAME: "MultiHalfCheetah-v0"
TEMPLATE: "./envs/race/assets/multi_half_cheetah.xml"

RNG_SEED: 42

USE_GPU: True
DEVICE: "cuda:0"

MAPPO:
  LR: 5.e-4
  CRITIC_LR: 5.e-4
  USE_LINEAR_LR_DECAY: False
  NUM_MINI_BATCH: 1

ENV:
  EPISODE_LENGTH: 1000
  DIMENSION: 2
  FORWARD_REWARD_WEIGHT: 1.0
  CTRL_COST_WEIGHT: 0.1
  RESET_NOISE_SCALE: 0.1
  USE_RELATIVE_OBS: True
  USE_NOISE: False

EMAT:
  AGENT_NUM: 1
  N_TRAINING_THREADS: 15
  N_ROLLOUT_THREADS: 15
  N_EVAL_ROLLOUT_THREADS: 1
  N_RENDER_ROLLOUT_THREADS: 1
  NUM_ENV_STEPS: 30e6

NETWORK:
  POLICY_DIST: "Beta"
  SHARE_POLICY: True
  USE_RELU: False
  HIDDEN_SIZE: 64
  LAYER_N: 2
  USE_CENTRALIZED_V: False

EVAL_PERIOD: 1