ENV_NAME: "MultiSwimmer-v0"
TEMPLATE: "./envs/assets/multi_swimmer.xml"

RNG_SEED: 42

USE_GPU: True
DEVICE: "cuda:0"

ENV:
  EPISODE_LENGTH: 1000
  DIMENSION: 3
  FORWARD_REWARD_WEIGHT: 1.0
  CTRL_COST_WEIGHT: 1.e-4
  RESET_NOISE_SCALE: 0.1
  USE_RELATIVE_OBS: False
  USE_NOISE: False
  
EMAT:
  AGENT_NUM: 1
  N_TRAINING_THREADS: 1
  N_ROLLOUT_THREADS: 1
  N_EVAL_ROLLOUT_THREADS: 1
  N_RENDER_ROLLOUT_THREADS: 1
  NUM_ENV_STEPS: 30e6

MAPPO:
  NUM_MINI_BATCH: 1

NETWORK:
  SHARE_POLICY: True
  USE_RELU: False
  HIDDEN_SIZE: 64
  LAYER_N: 2
  USE_CENTRALIZED_V: False

EVAL_PERIOD: 2